### ISSUE TITLE
Pars III 8x8

### ISSUE THREAD

**Issue by aayisee** [COVISART/Open-World-Content-Development#75]

**Comment by Nobatgeldi** [comment]
Umman rengi olucak, camuflage olmayacak Kule da iki namlu arasında kovanların çıkacağı yer olucak  static mesh olarak eklenecek Vizörün kapağı ayrı bir static mesh olucak.Kemikli modelde eklenecek.Her süspansiyon ayrı static mesh olucak, süpansiyon 3 kol olarak parçalanacak. Yeni model dosyası Havelsan tarafından gönderilecek.

**Comment by Nobatgeldi** [comment]
Body polygon sayisi yüksek, toplanlam polygon sayısı 100k geçmeyecek şelilde güncellenecek
