### ISSUE TITLE
Atış Hedef

### ISSUE THREAD

**Issue by aayisee** [COVISART/Open-World-Content-Development#82]
Atış   Hedef 1 | Varil
-- | --
Atış Hedef 2 | Konteyner
Atış Hedef 3 | Pano
Atış Hedef 4 | Yanmış Araç
Atış Hedef 5 |

**Comment by Nobatgeldi** [comment]
Atış   Hedef 1 | Varil
-- | --
Atış Hedef 2 | Konteyner
Atış Hedef 3 | Pano
Atış Hedef 4 | Yanmış Araç
Atış Hedef 5 |
